services:
  php:
    container_name: php
    image: imageweb
    volumes:
      - ./sources:/var/www/html
    ports:
      - 8000:80
      - 8001:81
    depends_on:
      - db
      
  db:
    container_name: db
    image: mysql:latest
    restart: always  
    environment:
      MYSQL_ROOT_PASSWORD: toor  
      MYSQL_DATABASE: mastack_db         
      MYSQL_USER: user1                 
      MYSQL_PASSWORD: userPass         
    ports:
      - "9906:3306"                      
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8080:80"
    restart: always
    environment:
      PMA_HOST: db
    depends_on:
      - db

volumes:
  db_data: {}

networks:
  MyDevStack: {}
  webnet: {}
